#ifndef DOMINI_TEST_TYPEDEFS_H
#define DOMINI_TEST_TYPEDEFS_H

typedef enum e_State {
	STATE_MENU,
	STATE_CREDITS,
	STATE_GAME,
	STATE_GAME_MOVE_POSSIBILITIES,
	STATE_END_GAME
} t_eState;

typedef enum e_Button {
	START,
	CREDITS,
	EXIT
} t_eButton;

#endif //DOMINI_TEST_TYPEDEFS_H
